language: objective-c
xcode_project: SUPSemVer.xcodeproj # path to your xcodeproj folder
xcode_scheme: SUPSemVer (iOS)
osx_image: xcode8
xcode_sdk: iphonesimulator10.0
script: ./test.sh
after_success:
    - bash <(curl -s https://codecov.io/bash)
